### ISSUE TITLE
Daily new deaths below one on log scale

### ISSUE THREAD

**Issue by kirienko** [fangohr/coronavirus-2020#3]
![image](https://user-images.githubusercontent.com/1487169/78580020-18eb6780-7832-11ea-840a-5369f349ef26.png)
The picture above is the output of `make_compare_plot_germany("Hamburg")`. There are two issues there. The first is that plots go beyond the frame, because functions' values are in the range (0, 1). The second issue is rather conceptual: it's unclear how should we understand the "_daily number of death_" in between zero and one. (It's okay for Schrödinger's cat but not for a real person.)

The same is applicable for all German Lands, i.e. that's an issue of `make_compare_plot_germany()`.

**Comment by fangohr** [comment]
Thanks for the feedback and critical analysis!

first: yes, fair point. On the other hand, if the values are below 1.0 (death per day), they are so small that we can't learn much from them. By setting the value to 1, we have more space in the y-direction to study the different curves.  (We could try setting the lower limit to 0.)

second: what is shown is a rolling average over 7 days (https://github.com/fangohr/coronavirus-2020/blob/50d2bdd427a6cdea56d3007659650ec54aae4ec0/coronavirus.py#L529), and thus you can get numbers below 1 if there was only one death but no deaths before and after. This was not documented, I added a comment to the [README.md](../README.md) now. Thanks for pointing this out!

**Comment by fangohr** [comment]
I tried to set the limit to 0 (or maybe 0.1 would be better). It doesn't look so nice for most plots, although I agree for Hamburg this is a bit special. 

I also added the 7-day rolling mean information to the y-axis label.  Thanks for the observation!
