### ISSUE TITLE
Line segments missing in log plot of daily new cases for Brandenburg

### ISSUE THREAD

**Issue by fangohr** [fangohr/coronavirus-2020#4]
Example Germany-Brandenburg with data from 7 April:

<img width="1014" alt="Screenshot 2020-04-07 at 07 34 04" src="https://user-images.githubusercontent.com/4489119/78633594-4bcd4400-78a2-11ea-9bfe-efa6b4641bf0.png">

No lines are plotting around day 5. Why? Why only here?

(version of code: commit 74772bf4cfd8d186fe2394191a188294c9e5c65b)

**Comment by kirienko** [comment]
BTW, is this still reproducible?

**Comment by fangohr** [comment]
Yes, checkout https://fangohr.github.io/coronavirus/html/Germany-Brandenburg-LK-Barnim.html
