### ISSUE TITLE
A long vertical space on all Germany pages after overview() function

### ISSUE THREAD

**Issue by kirienko** [fangohr/coronavirus-2020#42]
There is a huuuuge gap between cells number two and three in all  Germany-related notebooks (see [here](https://oscovida.github.io/html/Germany-Hamburg-SK-Hamburg.html) for Hamburg). It seems to be caused by `overview()` function.  I might be wrong, but it wasn't there previously. It is reproducible also in Binder.

**Comment by fangohr** [comment]
Thanks, well spotted! We had this problem before, and @RobertRosca fixed it. What was the solution at the time? It was some bizarre behaviour of the matplotlib SVG backend for plots with logs.

I'll also check to see what change may have created this deviation from previous behaviour.

**Comment by fangohr** [comment]
It possible that I have created the webpages with the wrong (conda) environment. It looks like if I do it again (the way I normally do) the error disappears. So please ignore this for now.

(Maybe I was using an older version of matplotlib by accident.)

**Comment by fangohr** [comment]
Problem disappeared when using the environment that was using `make dev-install`. So I presume I just made a mistake before.
